name: GitHub Actions - LeoEnergy Kiosk
run-name: ${{ github.actor }} is using GitHub Actions ðŸš€
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Make Actor and Repo lowercase
        run: |
          echo "ACTOR_LC=$(echo ${GITHUB_ACTOR} | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
          echo "REPO_LC=$(echo ${GITHUB_REPOSITORY} | tr '[:upper:]' '[:lower:]')" >>${GITHUB_ENV}
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js environment
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      # Install dependencies and build the Angular app
      - name: Install dependencies
        working-directory: frontend/kiosk
        run: npm install

      - name: Build Angular app
        working-directory: frontend/kiosk
        run: npm run build --prod -- --base-href /

      # Log in to GitHub Container Registry
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ env.ACTOR_LC }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push the Docker image
      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: ./frontend/kiosk
          file: ./frontend/kiosk/Dockerfile
          push: true
          tags: ghcr.io/${{ env.REPO_LC }}/kiosk:latest

